/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magadiastudentinfoui;

import java.time.LocalTime;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author main
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
        DataHandler.Students.CreateSamples();
        DataHandler.Students.CreateSubjects();
        SetEnrolledStudents();
        SetEnrolledCourses();
        SetStudentInfo();
        SetCourseInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        studentListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEnrolledStudents = new javax.swing.JTable();
        buttonEditStudent = new javax.swing.JButton();
        buttonRemoveStudent = new javax.swing.JButton();
        textFieldMn = new javax.swing.JTextField();
        textFieldLn = new javax.swing.JTextField();
        textFieldFn = new javax.swing.JTextField();
        labelMn = new javax.swing.JLabel();
        labelFn = new javax.swing.JLabel();
        labelLn = new javax.swing.JLabel();
        studentListLabel1 = new javax.swing.JLabel();
        labelGrade = new javax.swing.JLabel();
        labelSection = new javax.swing.JLabel();
        comboGrade = new javax.swing.JComboBox<>();
        comboSection = new javax.swing.JComboBox<>();
        labelCourseDay = new javax.swing.JLabel();
        comboBmonth = new javax.swing.JComboBox<>();
        comboBday = new javax.swing.JComboBox<>();
        comboByear = new javax.swing.JComboBox<>();
        labelAddress = new javax.swing.JLabel();
        textFieldAddress = new javax.swing.JTextField();
        labelContact = new javax.swing.JLabel();
        textFieldContact = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEnrolledSubjects = new javax.swing.JTable();
        buttonEditCourse = new javax.swing.JButton();
        buttonRemoveCourse = new javax.swing.JButton();
        courseListLabel = new javax.swing.JLabel();
        labelCourseCode = new javax.swing.JLabel();
        textFieldCourseCode = new javax.swing.JTextField();
        textFieldCourseName = new javax.swing.JTextField();
        labelCourseName = new javax.swing.JLabel();
        textFieldTeacher = new javax.swing.JTextField();
        labelTeacher = new javax.swing.JLabel();
        labelBdate1 = new javax.swing.JLabel();
        comboCourseDay = new javax.swing.JComboBox<>();
        labelCourseStart = new javax.swing.JLabel();
        comboCourseTimeStart = new javax.swing.JComboBox<>();
        labelCourseEnd = new javax.swing.JLabel();
        comboCourseTimeEnd = new javax.swing.JComboBox<>();
        buttonSave1 = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        schoolName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        schoolName.setText("CIIT Senior High School");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        studentListLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        studentListLabel.setText("Student List");

        tableEnrolledStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name", "Email Address", "Grade and Section"
            }
        ));
        tableEnrolledStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEnrolledStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEnrolledStudents);

        buttonEditStudent.setText("Edit Student");
        buttonEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditStudentActionPerformed(evt);
            }
        });

        buttonRemoveStudent.setText("Remove Student");
        buttonRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveStudentActionPerformed(evt);
            }
        });

        textFieldMn.setEditable(false);

        textFieldLn.setEditable(false);
        textFieldLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLnActionPerformed(evt);
            }
        });

        textFieldFn.setEditable(false);

        labelMn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelMn.setText("Middle Name");

        labelFn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelFn.setText("First Name");

        labelLn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelLn.setText("Last Name");

        studentListLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        studentListLabel1.setText("Administration Panel");

        labelGrade.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelGrade.setText("Grade");

        labelSection.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelSection.setText("Section");

        comboGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade 11", "Grade 12" }));

        comboSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maya", "Max", "Balance", "Rhythm", "Harmony", "Java", "Unity", "Vision", "Hue", "Symmetry", "Pattern", "Python" }));
        comboSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSectionActionPerformed(evt);
            }
        });

        labelCourseDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelCourseDay.setText("Day");

        comboBmonth.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboBmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        comboBday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboBday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboBday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBdayActionPerformed(evt);
            }
        });

        comboByear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboByear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));

        labelAddress.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelAddress.setText("Address");

        textFieldAddress.setEditable(false);

        labelContact.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelContact.setText("Contact Number");

        textFieldContact.setEditable(false);
        textFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContactActionPerformed(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelEmail.setText("Email");

        textFieldEmail.setEditable(false);

        buttonSave.setText("Save Changes");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        tableEnrolledSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Name", "Teacher", "Schedule"
            }
        ));
        tableEnrolledSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEnrolledSubjectsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableEnrolledSubjects);

        buttonEditCourse.setText("Edit Courses");
        buttonEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditCourseActionPerformed(evt);
            }
        });

        buttonRemoveCourse.setText("Remove Courses");
        buttonRemoveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveCourseActionPerformed(evt);
            }
        });

        courseListLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        courseListLabel.setText("Course List");

        labelCourseCode.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelCourseCode.setText("Course Code");

        textFieldCourseCode.setEditable(false);

        textFieldCourseName.setEditable(false);

        labelCourseName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelCourseName.setText("Course Name");

        textFieldTeacher.setEditable(false);

        labelTeacher.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelTeacher.setText("Teacher");

        labelBdate1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelBdate1.setText("Birthdate");

        comboCourseDay.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboCourseDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseDayActionPerformed(evt);
            }
        });

        labelCourseStart.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelCourseStart.setText("Time Start");

        comboCourseTimeStart.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboCourseTimeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseTimeStartActionPerformed(evt);
            }
        });

        labelCourseEnd.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelCourseEnd.setText("Time End");

        comboCourseTimeEnd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        buttonSave1.setText("Save Changes");
        buttonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSave1ActionPerformed(evt);
            }
        });

        buttonLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelGrade)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSection)
                                    .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(comboBday, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboByear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelContact)
                                            .addComponent(textFieldContact)))
                                    .addComponent(labelBdate1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentListLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonRemoveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(396, 396, 396))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmail)
                                    .addComponent(studentListLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelLn)
                                            .addComponent(textFieldLn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldFn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelFn))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelMn)
                                            .addComponent(textFieldMn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAddress))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(buttonEditCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCourseCode)
                                    .addComponent(textFieldCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCourseName)
                                    .addComponent(textFieldCourseName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonLogout)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(courseListLabel)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelTeacher)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelCourseDay)
                                                .addComponent(comboCourseDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelCourseStart)
                                                .addComponent(comboCourseTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelCourseEnd)
                                                .addComponent(comboCourseTimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(buttonSave1)
                                        .addComponent(textFieldTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(schoolName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolName)
                    .addComponent(buttonLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentListLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(courseListLabel)
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonRemoveCourse)
                                    .addComponent(buttonEditCourse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCourseCode)
                                    .addComponent(labelCourseName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(labelTeacher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCourseDay)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboCourseDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCourseStart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboCourseTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCourseEnd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboCourseTimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSave1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonRemoveStudent)
                                    .addComponent(buttonEditStudent))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelLn)
                                    .addComponent(labelFn)
                                    .addComponent(labelMn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldMn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelSection)
                                            .addComponent(labelGrade)
                                            .addComponent(labelBdate1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(comboGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(comboBmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboByear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelContact)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEmail)
                                        .addGap(34, 34, 34))
                                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSave)))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableEnrolledStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEnrolledStudentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableEnrolledStudentsMouseClicked

    private void buttonEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditStudentActionPerformed
        // TODO add your handling code here:
        String buttonText = buttonEditStudent.getText();
        editText = "Edit Student";
        saveText = "Submit Changes";
        
        if (buttonText.equals(editText)) {
            EditStudentInfo(true);
            buttonEditStudent.setText("Submit Changes");
        } else if (buttonText.equals(saveText)) {
            buttonEditStudent.setText("Edit Student");
            EditStudentInfo(false);
            System.out.println("Saving changes...");
        }
    }//GEN-LAST:event_buttonEditStudentActionPerformed

    private void buttonRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveStudentActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableEnrolledStudents.getModel();
        
        if (tableEnrolledStudents.getSelectedRowCount()==1) {
            //if single row is selected, then delete
            model.removeRow(tableEnrolledStudents.getSelectedRow());
            System.out.println("Removed " + textFieldLn.getText() + " from Student list.");
        } else if (tableEnrolledStudents.getRowCount()==0) {
            //if table is empty
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No students enrolled.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Please select student.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonRemoveStudentActionPerformed

    private void textFieldLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLnActionPerformed

    private void comboSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSectionActionPerformed

    private void comboBdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBdayActionPerformed

    private void textFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldContactActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void tableEnrolledSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEnrolledSubjectsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableEnrolledSubjectsMouseClicked

    private void buttonEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditCourseActionPerformed
        // TODO add your handling code here:
        String buttonText = buttonEditCourse.getText();
        editText = "Edit Courses";
        saveText = "Submit Changes";
        
        if (buttonText.equals(editText)) {
            EditCourseInfo(true);
            buttonEditCourse.setText("Submit Changes");
        } else if (buttonText.equals(saveText)) {
            buttonEditCourse.setText("Edit Courses");
            EditCourseInfo(false);
            System.out.println("Saving changes...");
        }
    }//GEN-LAST:event_buttonEditCourseActionPerformed

    //deleting course
    private void buttonRemoveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveCourseActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableEnrolledSubjects.getModel();
        
        if (tableEnrolledSubjects.getSelectedRowCount()==1) {
            //if single row is selected, then delete
            model.removeRow(tableEnrolledSubjects.getSelectedRow());
            System.out.println("Removed " + textFieldCourseName.getText() + " from Course list.");
        } else if (tableEnrolledSubjects.getRowCount()==0) {
            //if table is empty
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No courses available.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Please select Course.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonRemoveCourseActionPerformed

    private void buttonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSave1ActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        int input = javax.swing.JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to log out?");
        //0=yes, 1=no, 2=cancel
        if (input == 0) {
            this.setVisible(false);
            new Login().setVisible(true);
            System.out.println("Admin has logged out.");
        }
        else {
            this.setVisible(true);
        }

    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void comboCourseTimeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseTimeStartActionPerformed
        // TODO add your handling code here:
        comboCourseTimeStart.setToolTipText(comboCourseTimeStart.getSelectedItem().toString());
    }//GEN-LAST:event_comboCourseTimeStartActionPerformed

    private void comboCourseDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCourseDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }
    
    //enabling + disabling edit
    public void EditStudentInfo(boolean enable) {
        textFieldFn.setEditable(enable);
        textFieldMn.setEditable(enable);
        textFieldLn.setEditable(enable);
        comboGrade.setEnabled(enable);
        comboSection.setEnabled(enable);
        comboBmonth.setEnabled(enable);
        comboBday.setEnabled(enable);
        comboByear.setEnabled(enable);
        textFieldAddress.setEditable(enable);
        textFieldContact.setEditable(enable);
        textFieldEmail.setEditable(enable);
    }
    
    public void EditCourseInfo(boolean enable) {
        textFieldCourseCode.setEditable(enable);
        textFieldCourseName.setEditable(enable);
        textFieldTeacher.setEditable(enable);
        comboCourseDay.setEnabled(enable);
        comboCourseTimeStart.setEnabled(enable);
        comboCourseTimeEnd.setEnabled(enable);
    }
    
    //displaying Student Info from DataHandler
    public void SetStudentInfo() {
        firstName = DataHandler.Students.sampleStudent.getFirstName();
        middleName =  DataHandler.Students.sampleStudent.getMiddleName();
        lastName = DataHandler.Students.sampleStudent.getLastName();
        address = DataHandler.Students.sampleStudent.getAddress();
        birthDate = DataHandler.Students.sampleStudent.getBirthDate();
        contactNumber = DataHandler.Students.sampleStudent.getContactNumber();
        emailAddress = DataHandler.Students.sampleStudent.getEmailAddress();
        gradeLevel = DataHandler.Students.sampleStudent.getGradeLevel();
        section = DataHandler.Students.sampleStudent.getSection();
        
        textFieldFn.setText(firstName);
        textFieldMn.setText(middleName);
        textFieldLn.setText(lastName);
        textFieldAddress.setText(address);
        textFieldContact.setText(contactNumber);
        textFieldEmail.setText(emailAddress);
        
        comboBmonth.setSelectedIndex(birthDate.getMonth());
        comboBday.setSelectedIndex(birthDate.getDay()+16);
        comboByear.setSelectedIndex(birthDate.getYear()-1990);
        
        comboGrade.setSelectedIndex(gradeLevel-11);
        comboSection.setSelectedItem(section); 
        
        EditStudentInfo(false);
    }
    
    //displaying students in "Student List" table
    public void SetEnrolledStudents() {
        LinkedList<Student> studentsEnrolled = DataHandler.Students.sampleStudent.getStudentsEnrolled();
        DefaultTableModel studentListModel = (DefaultTableModel)tableEnrolledStudents.getModel();
        
        for(Student s:studentsEnrolled) {
            studentListModel.addRow( 
                new Object[] {
                    s.getLastName(),
                    s.getFirstName(),
                    s.getEmailAddress(),
                    s.getGradeLevel() + " - " + s.getSection()
                }
            );
        }
        
        tableEnrolledStudents.setModel(studentListModel);
    }
    
    //displaying Course Info from DataHandler
    public void SetCourseInfo() {
        for (Subject s:DataHandler.Students.availableSubjects) {
            String itemCode = s.getCode();
            textFieldCourseCode.setText(itemCode);
            String itemName = s.getName();
            textFieldCourseName.setText(itemName);
            String itemInstructor = s.getInstructor();
            textFieldTeacher.setText(itemInstructor);
            String itemDate = s.getDay();
            comboCourseDay.addItem(itemDate);
            String itemStart = s.getStart().toString();
            comboCourseTimeStart.addItem(itemStart);
            String itemEnd = s.getEnd().toString();
            comboCourseTimeEnd.addItem(itemEnd);
        }
        EditCourseInfo(false);
    }
    
    //displaying courses in "Course List" table
    public void SetEnrolledCourses() {
        LinkedList<Subject> subjectsEnrolled = DataHandler.Students.sampleStudent.getSubjectsEnrolled();
        DefaultTableModel model = (DefaultTableModel)tableEnrolledSubjects.getModel();
        
        for(Subject s:subjectsEnrolled) {
            model.addRow( 
                new Object[] {
                    s.getCode(),
                    s.getName(),
                    s.getInstructor(),
                    s.getStart() + " - " + s.getEnd()
                }
            );
        }
        
        tableEnrolledSubjects.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditCourse;
    private javax.swing.JButton buttonEditStudent;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonRemoveCourse;
    private javax.swing.JButton buttonRemoveStudent;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSave1;
    private javax.swing.JComboBox<String> comboBday;
    private javax.swing.JComboBox<String> comboBmonth;
    private javax.swing.JComboBox<String> comboByear;
    private javax.swing.JComboBox<String> comboCourseDay;
    private javax.swing.JComboBox<String> comboCourseTimeEnd;
    private javax.swing.JComboBox<String> comboCourseTimeStart;
    private javax.swing.JComboBox<String> comboGrade;
    private javax.swing.JComboBox<String> comboSection;
    private javax.swing.JLabel courseListLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBdate1;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelCourseCode;
    private javax.swing.JLabel labelCourseDay;
    private javax.swing.JLabel labelCourseEnd;
    private javax.swing.JLabel labelCourseName;
    private javax.swing.JLabel labelCourseStart;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFn;
    private javax.swing.JLabel labelGrade;
    private javax.swing.JLabel labelLn;
    private javax.swing.JLabel labelMn;
    private javax.swing.JLabel labelSection;
    private javax.swing.JLabel labelTeacher;
    private javax.swing.JLabel schoolName;
    private javax.swing.JLabel studentListLabel;
    private javax.swing.JLabel studentListLabel1;
    private javax.swing.JTable tableEnrolledStudents;
    private javax.swing.JTable tableEnrolledSubjects;
    private javax.swing.JTextField textFieldAddress;
    private javax.swing.JTextField textFieldContact;
    private javax.swing.JTextField textFieldCourseCode;
    private javax.swing.JTextField textFieldCourseName;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldFn;
    private javax.swing.JTextField textFieldLn;
    private javax.swing.JTextField textFieldMn;
    private javax.swing.JTextField textFieldTeacher;
    // End of variables declaration//GEN-END:variables
    private String firstName;
    private String middleName;
    private String lastName;
    private String address;
    private Date birthDate;
    private String contactNumber;
    private String emailAddress;
    private int gradeLevel;
    private String section;
   
    private String editText;
    private String saveText;
    
    private String courseCode;
    private String courseName;
    private String courseInstructor;
    private LocalTime start, end;
}
