/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magadiastudentinfoui;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author main
 */
public class StudentDashboardUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboardUI
     */
    public StudentDashboardUI() {
        initComponents();
        DataHandler.Students.CreateSamples();
        DataHandler.Students.CreateSubjects();
        SetInfo();
        InitializeAndSetCourses();
        SetEnrolledCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerLabel = new javax.swing.JLabel();
        schoolName = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        textFieldLn = new javax.swing.JTextField();
        textFieldFn = new javax.swing.JTextField();
        textFieldMn = new javax.swing.JTextField();
        labelLn = new javax.swing.JLabel();
        labelFn = new javax.swing.JLabel();
        labelMn = new javax.swing.JLabel();
        comboByear = new javax.swing.JComboBox<>();
        labelAddress = new javax.swing.JLabel();
        textFieldAddress = new javax.swing.JTextField();
        labelBdate = new javax.swing.JLabel();
        comboBmonth = new javax.swing.JComboBox<>();
        comboBday = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboGrade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        labelContact = new javax.swing.JLabel();
        textFieldContact = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        comboSection = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEnrolledSubjects = new javax.swing.JTable();
        buttonEdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboCoursesAvailable = new javax.swing.JComboBox<>();
        buttonRemoveCourse = new javax.swing.JButton();
        buttonAddCourse = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Panel Dashboard");

        registerLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        registerLabel.setText("Student Panel");

        schoolName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        schoolName.setText("CIIT Senior High School");

        labelName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelName.setText("Full Name");

        textFieldLn.setEditable(false);
        textFieldLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLnActionPerformed(evt);
            }
        });

        textFieldFn.setEditable(false);

        textFieldMn.setEditable(false);

        labelLn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelLn.setText("Last Name");

        labelFn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelFn.setText("First Name");

        labelMn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelMn.setText("Middle Name");

        comboByear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboByear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));

        labelAddress.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelAddress.setText("Address");

        textFieldAddress.setEditable(false);

        labelBdate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelBdate.setText("Birthdate");

        comboBmonth.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboBmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        comboBday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboBday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboBday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBdayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Grade");

        comboGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade 11", "Grade 12" }));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Section");

        labelContact.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelContact.setText("Contact Number");

        textFieldContact.setEditable(false);
        textFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContactActionPerformed(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelEmail.setText("Email");

        textFieldEmail.setEditable(false);

        comboSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maya", "Max", "Balance", "Rhythm", "Harmony", "Java", "Unity", "Vision", "Hue", "Symmetry", "Pattern", "Python" }));
        comboSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSectionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Enrolled Subjects");

        tableEnrolledSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Name", "Teacher", "Schedule"
            }
        ));
        tableEnrolledSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEnrolledSubjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEnrolledSubjects);
        if (tableEnrolledSubjects.getColumnModel().getColumnCount() > 0) {
            tableEnrolledSubjects.getColumnModel().getColumn(1).setResizable(false);
            tableEnrolledSubjects.getColumnModel().getColumn(2).setResizable(false);
        }

        buttonEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonEdit.setText("Edit Personal Information");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Course Available");

        comboCoursesAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCoursesAvailableActionPerformed(evt);
            }
        });

        buttonRemoveCourse.setText("Remove Courses");
        buttonRemoveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveCourseActionPerformed(evt);
            }
        });

        buttonAddCourse.setText("Add Courses");
        buttonAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddCourseActionPerformed(evt);
            }
        });

        buttonLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonEdit))
                            .addComponent(labelLn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboByear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelBdate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAddress))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelContact)
                                    .addComponent(textFieldContact)
                                    .addComponent(comboGrade, 0, 129, Short.MAX_VALUE))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail)
                            .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldLn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textFieldFn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelMn)
                                            .addComponent(textFieldMn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonRemoveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboCoursesAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(schoolName)
                                .addGap(271, 271, 271)
                                .addComponent(buttonLogout)))
                        .addContainerGap(24, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerLabel)
                .addGap(419, 419, 419))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(schoolName)
                    .addComponent(buttonLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelContact)
                            .addComponent(labelEmail))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelName)
                                .addComponent(buttonEdit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textFieldLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldMn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLn)
                            .addComponent(labelFn)
                            .addComponent(labelMn))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBdate)
                            .addComponent(labelAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboByear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonRemoveCourse)
                            .addComponent(buttonAddCourse)))
                    .addComponent(comboCoursesAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLnActionPerformed

    private void textFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldContactActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        String buttonText = buttonEdit.getText();
        editText = "Edit Personal Information";
        saveText = "Submit Changes";
        
        if (buttonText.equals(editText)) {
            EditEnableDisable(true);
            buttonEdit.setText("Submit Changes");
        } else if (buttonText.equals(saveText)){
            buttonEdit.setText("Edit Personal Information");
            EditEnableDisable(false);
            GetInfo();
            SaveInfo();
            System.out.println("Saving Changes...");
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        int input = javax.swing.JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to log out?");
        //0=yes, 1=no, 2=cancel
        if (input == 0) {
            this.setVisible(false);
            new Login().setVisible(true);
            System.out.println("User has logged out.");
        }
        else {
            this.setVisible(true);
        }
        
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void comboSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSectionActionPerformed

    private void buttonAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddCourseActionPerformed
        // TODO add your handling code here:
        int input = javax.swing.JOptionPane.showConfirmDialog(rootPane, "Add " + (String) comboCoursesAvailable.getSelectedItem() + " to Enrolled Subjects?");
        //0=yes, 1=no, 2=cancel
        if (input == 0) {
            DefaultTableModel model = (DefaultTableModel)tableEnrolledSubjects.getModel();
            List<String> courses = new ArrayList<String>();

            courses.add((String) comboCoursesAvailable.getSelectedItem());
            model.addRow(courses.toArray());

            tableEnrolledSubjects.setModel(model);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_buttonAddCourseActionPerformed

    private void buttonRemoveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveCourseActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableEnrolledSubjects.getModel();
        
        if (tableEnrolledSubjects.getSelectedRowCount()==1) {
            //if single row is selected, then delete
            model.removeRow(tableEnrolledSubjects.getSelectedRow());
        } else if (tableEnrolledSubjects.getRowCount()==0) {
            //if table is empty
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No courses available.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Please select Course.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonRemoveCourseActionPerformed

    private void comboCoursesAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCoursesAvailableActionPerformed
        // TODO add your handling code here:
        comboCoursesAvailable.setToolTipText(comboCoursesAvailable.getSelectedItem().toString());
    }//GEN-LAST:event_comboCoursesAvailableActionPerformed

    private void tableEnrolledSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEnrolledSubjectsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableEnrolledSubjectsMouseClicked

    private void comboBdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboardUI().setVisible(true);
            }
        });
    }
    
    //enabling + disabling edit
    public void EditEnableDisable(boolean enable) {
        textFieldFn.setEditable(enable);
        textFieldMn.setEditable(enable);
        textFieldLn.setEditable(enable);
        comboGrade.setEnabled(enable);
        comboSection.setEnabled(enable);
        comboBmonth.setEnabled(enable);
        comboBday.setEnabled(enable);
        comboByear.setEnabled(enable);
        textFieldAddress.setEditable(enable);
        textFieldContact.setEditable(enable);
        textFieldEmail.setEditable(enable);
    }
    
    //displaying info from DataHandler
    public void SetInfo() {
        firstName = DataHandler.Students.sampleStudent.getFirstName();
        middleName =  DataHandler.Students.sampleStudent.getMiddleName();
        lastName = DataHandler.Students.sampleStudent.getLastName();
        address = DataHandler.Students.sampleStudent.getAddress();
        birthDate = DataHandler.Students.sampleStudent.getBirthDate();
        contactNumber = DataHandler.Students.sampleStudent.getContactNumber();
        emailAddress = DataHandler.Students.sampleStudent.getEmailAddress();
        gradeLevel = DataHandler.Students.sampleStudent.getGradeLevel();
        section = DataHandler.Students.sampleStudent.getSection();
        
        textFieldFn.setText(firstName);
        textFieldMn.setText(middleName);
        textFieldLn.setText(lastName);
        textFieldAddress.setText(address);
        textFieldContact.setText(contactNumber);
        textFieldEmail.setText(emailAddress);
        
        comboBmonth.setSelectedIndex(birthDate.getMonth());
        comboBday.setSelectedIndex(birthDate.getDay()+16);
        comboByear.setSelectedIndex(birthDate.getYear()-1990);
        
        comboGrade.setSelectedIndex(gradeLevel-11);
        comboSection.setSelectedItem(section); 
        
        System.out.println(birthDate);
        System.out.println(gradeLevel);
        EditEnableDisable(false);
    }
    
    //getting info from edited info
    public void GetInfo() {
        firstName = textFieldFn.getText();
        middleName = textFieldMn.getText();
        lastName = textFieldLn.getText();
        address = textFieldAddress.getText();
        contactNumber = textFieldContact.getText();
        emailAddress = textFieldEmail.getText();
        
        int bMonth = comboBmonth.getSelectedIndex();
        int bDay = comboBday.getSelectedIndex() +1;
        int bYear = comboByear.getSelectedIndex() +1990;
        birthDate = new Date(bMonth, bDay, bYear);
        
        gradeLevel = comboGrade.getSelectedIndex() + 11;
        section = comboSection.toString();
        
        System.out.println(birthDate);
    }
    
    //saving info
    public void SaveInfo() {
        DataHandler.Students.sampleStudent.setFirstName(firstName);
        DataHandler.Students.sampleStudent.setMiddleName(middleName);
        DataHandler.Students.sampleStudent.setLastName(lastName);
        DataHandler.Students.sampleStudent.setAddress(address);
        DataHandler.Students.sampleStudent.setContactNumber(contactNumber);
        DataHandler.Students.sampleStudent.setEmailAddress(emailAddress);
        DataHandler.Students.sampleStudent.setBirthDate(birthDate);
        DataHandler.Students.sampleStudent.setGradeLevel(gradeLevel);
        DataHandler.Students.sampleStudent.setSection(section);
        
        System.out.println("Full Name: " + this.lastName + ", " + this.firstName + " " + this.middleName);
        System.out.println("Birthday: " + this.birthDate);
        System.out.println("Address: " + this.address);
        System.out.println("Contact Number: " + this.contactNumber);
        System.out.println("Email: " + this.emailAddress);
    }
    
    //displaying courses in "Courses Avaiallaeble" combo box
    public void InitializeAndSetCourses() {
        DataHandler.Students.CreateSubjects();
        
        for(Subject s:DataHandler.Students.availableSubjects) {
            String item = s.getCode() + " - " + s.getName() + " - " + s.getInstructor();
            comboCoursesAvailable.addItem(item);
        }
    }
    
    //displaying courses in "Enrolled Subecjst" table
    public void SetEnrolledCourses() {
        LinkedList<Subject> subjectsEnrolled = DataHandler.Students.sampleStudent.getSubjectsEnrolled();
        DefaultTableModel model = (DefaultTableModel)tableEnrolledSubjects.getModel();
        
        for(Subject s:subjectsEnrolled) {
            model.addRow( 
                new Object[] {
                    s.getCode(),
                    s.getName(),
                    s.getInstructor(),
                    s.getStart() + " - " + s.getEnd()
                }
            );
        }
        
        tableEnrolledSubjects.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddCourse;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonRemoveCourse;
    private javax.swing.JComboBox<String> comboBday;
    private javax.swing.JComboBox<String> comboBmonth;
    private javax.swing.JComboBox<String> comboByear;
    private javax.swing.JComboBox<String> comboCoursesAvailable;
    private javax.swing.JComboBox<String> comboGrade;
    private javax.swing.JComboBox<String> comboSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBdate;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFn;
    private javax.swing.JLabel labelLn;
    private javax.swing.JLabel labelMn;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel schoolName;
    private javax.swing.JTable tableEnrolledSubjects;
    private javax.swing.JTextField textFieldAddress;
    private javax.swing.JTextField textFieldContact;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldFn;
    private javax.swing.JTextField textFieldLn;
    private javax.swing.JTextField textFieldMn;
    // End of variables declaration//GEN-END:variables
    private String firstName;
    private String middleName;
    private String lastName;
    private String address;
    private Date birthDate;
    private String contactNumber;
    private String emailAddress;
    private int gradeLevel;
    private String section;
   
    private String editText;
    private String saveText;
}
